apiVersion: v1
kind: Namespace
metadata:
  name: tatanka27
---
apiVersion: v1
kind: Secret
metadata:
  name: db-access
  namespace: tatanka27
type: Opaque
stringData:
  username: user
  password: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tatanka27
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: data_from_vk
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-access
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-access
                  key: password
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tatanka27
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tatanka27
  name: datafromvk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datafromvk
  template:
    metadata:
      labels:
        app: datafromvk
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: datafromvk
          image: tatanka27/datafromvk
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/data_from_vk
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: db-access
                  key: username
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-access
                  key: password
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: datafromvk
  namespace: tatanka27
spec:
  type: NodePort
  selector:
    app: datafromvk
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30007